### ISSUE TITLE
Where is the License?

### ISSUE THREAD

**Issue by TechnikEmpire** [Selinux24/SharpDX-Tests#71]
Stumbled on this project, looks cool but I can't find the license. Can you specify a license?

**Comment by Selinux24** [comment]
I'm thinking on it. It has a lot of third parties content, and I have to do something about that thing

**Comment by TechnikEmpire** [comment]
Alright cool thanks for the reply. I'll watch the repo if I haven't already.

**Comment by suprafun** [comment]
Sorry to bother you, I was just wondering if you have come to a decision yet on the license ? I would like to study this project if you don't mind, so I can learn about making my own game engine. Thank-you.

**Comment by Selinux24** [comment]
Done! 1ef7f443b34019e599621719ebcd1c20edbc6beb

**Comment by TechnikEmpire** [comment]
Thank you!
