### ISSUE TITLE
Can I export animation as video or a series of image files

### ISSUE THREAD

**Issue by zydjohnHotmail** [Selinux24/SharpDX-Tests#77]
Hello:
I found this repo, it seems to be interesting.  But I want to know if I can export some of the animaitons either as a video (MP4 format) for as a series of image files (PNG format).
I know I can use 3rd party screen recorder to do the job, but I want to see if I can have some built-in feature for this.
Thanks,

**Comment by Selinux24** [comment]
It's not planed, for now
